// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PJ_webservice_CRUD.Models;

namespace PJ_webservice_CRUD.Migrations
{
    [DbContext(typeof(PO_DetailContext))]
    partial class PO_DetailContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PJ_webservice_CRUD.Models.Category", b =>
                {
                    b.Property<string>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("CategoryID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("PJ_webservice_CRUD.Models.PO_Detail", b =>
                {
                    b.Property<string>("PO_DetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("PO_Date");

                    b.Property<string>("PO_HeaderPO_SupplyID")
                        .IsRequired();

                    b.Property<int>("PO_PriceOfUnit");

                    b.Property<int>("PO_Quantity");

                    b.Property<string>("ProductID")
                        .IsRequired();

                    b.HasKey("PO_DetailID");

                    b.HasIndex("PO_HeaderPO_SupplyID");

                    b.HasIndex("ProductID");

                    b.ToTable("PO_Details");
                });

            modelBuilder.Entity("PJ_webservice_CRUD.Models.PO_Header", b =>
                {
                    b.Property<string>("PO_SupplyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("PO_Adress")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PO_Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PO_SupplyName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PO_Tel")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("PO_SupplyID");

                    b.ToTable("PO_Header");
                });

            modelBuilder.Entity("PJ_webservice_CRUD.Models.Product", b =>
                {
                    b.Property<string>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Amount");

                    b.Property<string>("CategoryID");

                    b.Property<string>("ImgURL");

                    b.Property<int>("Price");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("PJ_webservice_CRUD.Models.PO_Detail", b =>
                {
                    b.HasOne("PJ_webservice_CRUD.Models.PO_Header", "PO_Header")
                        .WithMany()
                        .HasForeignKey("PO_HeaderPO_SupplyID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PJ_webservice_CRUD.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PJ_webservice_CRUD.Models.Product", b =>
                {
                    b.HasOne("PJ_webservice_CRUD.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID");
                });
#pragma warning restore 612, 618
        }
    }
}
